name: Github auto Deployment
on:
  push:
    branches: [master]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: testing
        run: |
          whoami
  deploying:
    runs-on: ubuntu-latest
    steps:
      - name: sshing into server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd myApp/Coding-Quizz
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/github_ssh
            git pull
            nohup npm start &
            echo "DONE"
